### ISSUE TITLE
Request for a `core-foundation` example

### ISSUE THREAD

**Issue by LoganDark** [mrmekon/fruitbasket#20]
I believe it would be helpful to have a `core-foundation` example (as in, that one project created solely for Servo's use, but that is also useful for general purposes) as those are the bindings I plan on using for my own projects.

As those seem to be the only bindings out there for macOS (as far as I know), it's only natural that it's what you'd use after fruitbasket, in my opinion. (assuming you're directly making a native macOS app)

It may still be a little opinionated, but I would like to request an example showing how to use `core-foundation` with fruitbasket.

**Comment by mrmekon** [comment]
I'll try to look into this when I get time, but I haven't used `core-foundation` myself so I don't have anything to base an example on at the moment.  I used a mixture of the `objc` and `cocoa` crates for my native macOS development.

A very unclean example of using all three together is here: https://github.com/mrmekon/connectr/blob/master/src/osx/mod.rs

Connectr was an experiment that led to the creation of fruitbasket in the first place, and is very much an evolution of a bunch of different approaches to native macOS development in Rust.  My preference now would be to skip the `cocoa` crate and do everything manually with `objc`.  It's a very raw interface, which means significantly harder to work with, but on the other hand it means you don't have to wait for a library maintainer to add support for whatever interfaces you might need.

My touchbar library, `rubrail`, uses `objc` more extensively, and its example uses `fruitbasket`: https://github.com/mrmekon/rubrail-rs/blob/master/examples/example.rs

**Comment by LoganDark** [comment]
I don't even know Objective-C so I can't just use that stuff so easily...

Plus, trying to code with `objc` directly is like abandoning all of Rust's safety guarantees and coding directly in Objective-C. Yeah, I could spend a long time writing abstractions but at that point it may as well become its own library.

I also gave up on core foundation because they're incomplete and confusing to use.

**Comment by LoganDark** [comment]
Since posting this issue I've settled on libui and just a _little_ bit of `objc`, so I personally don't need the core foundation examples anymore. Feel free to reopen this issue if you feel like they would be particularly useful; otherwise...
