### ISSUE TITLE
Should there be a HiDPI convenience method?

### ISSUE THREAD

**Issue by LoganDark** [mrmekon/fruitbasket#21]
Currently, HiDPI support can be declared to macOS by specifying two properties in the plist:

```rust
	.plist_key("NSHighResolutionCapable", "True")
	.plist_key("NSPrincipleClass", "NSApplication")
```

Without these two properties, macOS will default to displaying your application in 1x mode and scaling it up on Retina displays. This makes it really blurry and honestly looks bad.

Compare this, the default:
![image](https://user-images.githubusercontent.com/4723091/90957811-01a9c100-e445-11ea-8158-dc0297aa1e46.png)

To this, with the properties:
![image](https://user-images.githubusercontent.com/4723091/90957803-fb1b4980-e444-11ea-8b4b-9d401052649f.png)

As you can see, there is a shockingly large difference between the two, and the first one definitely doesn't look very appealing.

Even though fruitbasket is not itself a GUI library, it's still used in applications that do use GUI libraries, so perhaps there should be a method in the builder specifically for this. Something like `fn hidpi(&mut self, doit: bool)`. You'd be hard-pressed to find a Mac _without_ a Retina display these days, and not everyone knows the HiDPI trick.

What are your thoughts on this? Is this within the scope of fruitbasket to provide these convenience methods, even though they have nothing to do with fruitbasket itself? I'd argue that it is, since fruitbasket is intended to bootstrap applications that often need these properties, but I'd love to hear your thoughts on the matter.

**Comment by mrmekon** [comment]
Yes, I think this is reasonable.  I don't want it to drift into a whole UI toolkit, but helpers for common and non-obvious settings like this are a good idea.
