### ISSUE TITLE
Handling openFile events

### ISSUE THREAD

**Issue by woelper** [mrmekon/fruitbasket#25]
This is actually more of a question, but I am very happy to contribute an example once I can work out if this is possible.
There is already a nice example how to register URL callbacks, but I am unable to find a way to register and handle opening filetypes.

I've read https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/DocumentInteraction_TopicsForIOS/Articles/RegisteringtheFileTypesYourAppSupports.html#//apple_ref/doc/uid/TP40010411-SW1 and believe I can add all the relevant plist entries, but I am unsure about actually handling `application:openFile:` events. Would this be something that is possible using fruitbasket?

**Comment by jorgenpt** [comment]
@woelper If you want to try my branch that implements this support (I’ve opened a pull request), you can see the example in this commit (including the Cargo.toml syntax for depending on my branch): https://github.com/jorgenpt/bichrome/commit/1e156b3ffd69b3dc7fd9f53c25791743e8b5dfda

In bichrome I only handle pre-existing extensions (web pages) and I don’t use fruitbasket for the Info.plist (I ship my app as a bundle), so I don’t have a good example for the registration itself. You can see my Info.plist here, if that helps: https://github.com/jorgenpt/bichrome/blob/8bab47091d48473b6f7cd4764966145d3e6399ef/assets/bichrome.app/Contents/Info.plist

**Comment by woelper** [comment]
@jorgenpt Amazing, that you so much! This was very helpful!
