### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by woelper** [mrmekon/fruitbasket#28]
Hello!
Would it be possible to publish the most recent version on crates.io if it's considered stable enough? I depend on this crate for handling file open functionality on Mac OS (https://github.com/woelper/oculante/issues/16) and would be very happy if I could remove the git dependency! Thanks in advance!

**Comment by mrmekon** [comment]
welp, that took forever, but v0.10.0 is released and published.  Sorry for the nearly year long delay...

**Comment by woelper** [comment]
You rock, thanks so much!
