### ISSUE TITLE
Support for nested plist array definitions

### ISSUE THREAD

**Issue by gwihlidal** [mrmekon/fruitbasket#9]
Hi! First off, awesome crate - thanks so much for making it.

I want to register a custom URI protocol to my app (i.e. CFBundleURLTypes), but the plist api in fruitbasket doesn't appear to support this directly, or by allowing arrays instead of just strings.
https://github.com/mrmekon/fruitbasket/blob/master/src/osx.rs#L380

Basically, I need to represent something like this:
```
<key>CFBundleURLTypes</key>
<array>
    <dict>
        <key>CFBundleURLName</key>
        <string>My Proto</string>
        <key>CFBundleURLSchemes</key>
        <array>
            <string>myproto</string>
        </array>
    </dict>
</array>
```

Do you have ideas on the best way to go about this?

**Comment by mrmekon** [comment]
Sorry about being 8 months late... I apparently don't get issue notifications.

I guess you have probably moved on by now, but I just added some manner of official support for this to fruitbasket.  You can add raw strings to the plist, and register to receive some callbacks from the Apple event system.  There's a new binary in the example files that registers a custom URI.

See pull request #10 and the [register_url example](https://github.com/mrmekon/fruitbasket/blob/master/examples/register_url.rs).

It isn't published on crates.io yet.
